config/routes.rb
Rails.application.routes.draw do
  resources :ducks

  root 'topics#index'
  resources :topics do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  get '/about/', to: 'topics#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/duck.rb
class Duck < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  before_action :set_duck, only: [:show, :edit, :update, :destroy]

  # GET /ducks
  # GET /ducks.json
  def index
    @ducks = Duck.all
  end

  # GET /ducks/1
  # GET /ducks/1.json
  def show
  end

  # GET /ducks/new
  def new
    @duck = Duck.new
  end

  # GET /ducks/1/edit
  def edit
  end

  # POST /ducks
  # POST /ducks.json
  def create
    @duck = Duck.new(duck_params)

    respond_to do |format|
      if @duck.save
        format.html { redirect_to @duck, notice: 'Duck was successfully created.' }
        format.json { render :show, status: :created, location: @duck }
      else
        format.html { render :new }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ducks/1
  # PATCH/PUT /ducks/1.json
  def update
    respond_to do |format|
      if @duck.update(duck_params)
        format.html { redirect_to @duck, notice: 'Duck was successfully updated.' }
        format.json { render :show, status: :ok, location: @duck }
      else
        format.html { render :edit }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ducks/1
  # DELETE /ducks/1.json
  def destroy
    @duck.destroy
    respond_to do |format|
      format.html { redirect_to ducks_url, notice: 'Duck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duck
      @duck = Duck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duck_params
      params.require(:duck).permit(:title, :description)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.sort_by { |topic| topic.votes.count }.reverse
  end

  # GET /topics/1
  # GET /topics/1.json
  def show; end

  def about; end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit; end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
end

  def downvote
    @topic = Topic.find(params[:id])
    @topic.votes.last.destroy
    redirect_to(topics_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ducks_helper.rb
module DucksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/ducks/_form.html.erb
<%= form_for(duck) do |f| %>
  <% if duck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duck.errors.count, "error") %> prohibited this duck from being saved:</h2>

      <ul>
      <% duck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ducks/edit.html.erb
<h1>Editing Duck</h1>

<%= render 'form', duck: @duck %>

<%= link_to 'Show', @duck %> |
<%= link_to 'Back', ducks_path %>

app/views/ducks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ducks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ducks.each do |duck| %>
      <tr>
        <td><%= duck.title %></td>
        <td><%= duck.description %></td>
        <td><%= link_to 'Show', duck %></td>
        <td><%= link_to 'Edit', edit_duck_path(duck) %></td>
        <td><%= link_to 'Destroy', duck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duck', new_duck_path %>

app/views/ducks/new.html.erb
<h1>New Duck</h1>

<%= render 'form', duck: @duck %>

<%= link_to 'Back', ducks_path %>

app/views/ducks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @duck.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @duck.description %>
</p>

<%= link_to 'Edit', edit_duck_path(@duck) %> |
<%= link_to 'Back', ducks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suggestotron</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/about.html.erb
<p>
  <strong>About</strong>
</p>
<p>
Welcome!
</p>
<%= link_to 'Back', topics_path %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic %></td>

        <td><%= pluralize(topic.votes.count, "vote") %></td>
   <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
<td><%= button_to '-1', downvote_topic_path(topic), method: :post %></td>
        <td><%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>


<br>

<%= link_to 'about', about_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>